### ISSUE TITLE
Woocommerce - Error indexing prices via API

### ISSUE THREAD

**Issue by ivan-doofinder** [doofinder/doofinder-woocommerce#120]
Cuando se indexa desde el plugin usando nuestra API (doofapi), los precios se envían como cadena de texto y deberían de ser float.

Ejemplo en cliente US - lensgogo.me

**Comment by Aitor-Corrales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-woocommerce/120?planning-poker) with Zenhub @Aitor-Corrales @abraham-doofinder @ivan-doofinder @eduardogomez97 @sofia-doofinder @pedromcp90
