### ISSUE TITLE
Woocommerce Wizard Setup final step bug

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-woocommerce#128]
I have found a bug in the wizard setup that occurs when a customer already has an installation done. 
Before when this was the case when you click on wizard setup again it allowed you to repeat the process creating a new store.
Currently if we click on it, the 5th step always appears.

This may be because the current step is saved in the client database and is not being reset once the process is finished.

![setupwizard4.png](https://images.zenhubusercontent.com/62cc16b840afcb2bb6a9b5b2/2f19b9af-be0e-40d8-a671-b752851454a5)

**Comment by ivan-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-woocommerce/128?planning-poker) with Zenhub @abraham-doofinder @Aitor-Corrales @alvanieto @eduardogomez97 @ivan-doofinder @pedromcp90 @sofia-doofinder
