### ISSUE TITLE
[WooCommerce] Indexation fails on multilanguage site while indexing the second language

### ISSUE THREAD

**Issue by pedromcp90** [doofinder/doofinder-woocommerce#129]
Investigate why the indexation fails while indexing the second language.

**Comment by ivan-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-woocommerce/129?planning-poker) with Zenhub @abraham-doofinder @Aitor-Corrales @alvanieto @eduardogomez97 @ivan-doofinder @pedromcp90 @sofia-doofinder

**Comment by pedromcp90** [comment]
The problem occurs only after launching indexation for a specific language and then launching indexation for all languages. If you retry, it works as expected the second time.
The error seems to happen while creating the temporary index through the API. 
Returned error:
{"error":{"code":"not_found","details":{"resource":"TemporaryIndex"}}}
