### ISSUE TITLE
Woocommerce prices type must be float, not string

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-woocommerce#145]
It has been found that in woocommerce plugin now prices are string type. This must be fixed and instead of string the prices must be float type.

Related support issue: https://github.com/doofinder/support/issues/182

**Comment by pedromcp90** [comment]
Already solved in doofApi by the following PRs:
- https://github.com/doofinder/doofAPI/pull/1185
- https://github.com/doofinder/doofAPI/pull/1194
- https://github.com/doofinder/doofAPI/pull/1198

**Comment by pedromcp90** [comment]
I've been making some indexing tests, and it seems that the body we are sending to doofApi is including prices as float, not as string.

This is a bulk update request, where you can see the that the price attribute is sent as float:
![image.png](https://images.zenhubusercontent.com/62cd7219d361726b07a6c950/7b05f12e-5e54-4a93-abf6-57ebf3c2d694)

And this is an update on save request:
![image.png](https://images.zenhubusercontent.com/62cd7219d361726b07a6c950/cd7a2475-7114-4876-8e9d-944d7266a48c)

**Comment by pedromcp90** [comment]
As @albertodoofinder requested, I've done some local tests with doofApi to check what data is being sent while creating or updating products.
This is what doofApi receives on Bulk update / create:
![image.png](https://images.zenhubusercontent.com/62cd7219d361726b07a6c950/bc407dce-b7a8-4198-ba03-178b1e27bc03)
And this is what doofApi receives on Update on save (single create):
![image.png](https://images.zenhubusercontent.com/62cd7219d361726b07a6c950/c01ea74c-c986-40e3-b6c2-f7fe23d2354b)

So finally, we can conclude that the prices are being sent correctly in the current plugin release.
