### ISSUE TITLE
View installed Woommerce and Wordpress plugin version

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-woocommerce#147]
It is required to implement a plugin version endpoint for Woocommerce and Wordpress to help resolution of support tickets.

The endpoint must provide the current installed version of the plugin. It would be using a similar approach to what is done with the config url on other platforms such as Prestashop just adding to shop url _/modules/doofinder/config.php_ or Magento adding to shop url _/rest/default/V1/doofinder/config_.

**Comment by pedromcp90** [comment]
This functionality is already implemented for both plugins.
You can check the version accessing the following endpoints:
- Doofinder for WordPress: **/feed/doofinder-for-wp-confirmation**
- Doofinder for Woocommerce **/feed/doofinder-config/**
