### ISSUE TITLE
[Wordpress / Woocommerce]  Check data migration process when a customer upgrades to the new version

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-woocommerce#170]
Some customers have reported that they have had some problems when upgrading to the new plugin that the datasource/index type has not been changed and the credentials in the store.options have not been set.

We need to check the process to see in which cases it may fail and add that the credentials are only created when the user is an Administrator or has permissions for API REST management.

Also add in the documentation that only users with Administrator permissions (or who can access the API) must create the password.

**Comment by pedromcp90** [comment]
We must not delete all the DataSources, instead, we must update the DataSources that belong to a product type DataType, in this way the file DataSources that the client may have configured would not be lost.

**Comment by eduardogomez97** [comment]
After an investigation we have developed a solution for data migration. There are some cases of misconfiguration where it can fail related to search_engines and multi-language, but these are extreme cases and we have created logs to be able to identify them.

We have also added a way to force migration if the process is not completed correctly. To do this we just have to add the flag &force_normalization=true to the admin URL:

EX: https://84a41da4-3ffb-463e-b4b8-d9e4f228d447.clouding.host/wp-admin/admin.php?page=doofinder_for_wp&force_normalization=true

We will know that we have launched the migration because a header will appear indicating it.

This is delicate and should only be supported in the cases that when updating the plugin there has been an error. The good thing is that the strange cases will now have better logs and we will be able to fine tune.

**Comment by eduardogomez97** [comment]
Another case we have found that fails is when it already detects a REST API password called doofinder. This only happens when the plugin has been rolled back and the databases have not been sanitized. But it is warned with this error:

![Image](https://github.com/doofinder/doofinder-woocommerce/assets/22339368/e187208d-2a8b-4819-8280-8055754e73dc)

**Comment by pedromcp90** [comment]
With [doomanager#5122](https://github.com/doofinder/doomanager/pull/5122) we have made improvements to the way normalization is performed in Doomanager to prevent the removal of existing file-type feeds.
