### ISSUE TITLE
Wordpress & Woocommerce in WP 6.3

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-woocommerce#189]
This task consists of checking our compatibility with Wordpress 6.3 to be able to update the profile at https://es.wordpress.org/plugins/doofinder-for-woocommerce/.

At first sight it seems that we are compatible, but we should investigate if we can improve the code and check the main points of the 6.3 change.

Once everything is correct, make an update indicating that we are compatible.

**Comment by vferrero** [comment]
I have reviewed all the changes in version 6.3.1 of Wordpress and I have been able to verify that we are compatible with this version.
Most of the changes in this version of Wordpress are slight cache performance improvements, visual improvements to the installer, and the most notable change would be that it no longer supports PHP5. Minimal now requires PHP7. So we have no problem updating:

Wordpress: 6.3.1
PHP requires: 7.0.0
