### ISSUE TITLE
Wordpress & Woocommerce  - Wizard Setup dont update search engine

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-woocommerce#193]
We have detected a problem when launching the Wizard Setup and it is that when launching a new installation it is created perfectly. But it does not update the search engine in the Wordpress database so in the administrator panel still shows the old one. This causes that when launching plugin requests to doomanager are made with the old search engine and do not get to make changes such as reset credentials, etc..

We need to investigate why it is not updated and fix it.

**Comment by vferrero** [comment]
It has been verified both locally and in production that the hashid update works correctly. Surely when it failed it would be because something failed locally when I was testing it.
Everything works correctly!
