### ISSUE TITLE
Wordpress & Woocommerce - Index Banner bug

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-woocommerce#194]
https://github.com/doofinder/support/issues/1392

We have seen with support that sometimes the banner stays much longer even if the indexing fails. This only happens in very specific cases when the first indexing gives a 401.

It is not critical but we would have to check why it takes so long to stop the banner.

**Comment by sofia-doofinder** [comment]
@eduardogomez97 creo que esto es este mismo error no? https://github.com/doofinder/support/issues/2556

lo digo por cerrar esta issue

**Comment by sofia-doofinder** [comment]
@eduardogomez97 te escribo de nuevo para que me confirmes please

**Comment by eduardogomez97** [comment]
Sí @sofia-doofinder 

Me refería justo a ese error
