### ISSUE TITLE
Wordpress & Woocommerce - Index Banner Bug

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-woocommerce#195]
We have seen with support (https://github.com/doofinder/support/issues/1392) that sometimes the banner stays much longer even if the indexing fails. This only happens in very specific cases when the first indexing gives a 401.
It is not critical but we would have to check why it takes so long to stop the banner.

**Comment by vferrero** [comment]
The problem was in the callback URL structure, the EUR currency was being fixed instead of using the system's own currency (woocommerce or wordpress), so when the callback request was launched it never matched the currency and the process was never marked as "processed".

**Comment by vferrero** [comment]
The data indexing completion callback request is now working correctly.


![Image](https://github.com/doofinder/doofinder-woocommerce/assets/5503117/4ec36dec-f59e-4841-b311-367a4cee43f0)
