### ISSUE TITLE
[Wordpress / Woocommerce] Detection of plugins that disable the wordpress API

### ISSUE THREAD

**Issue by vferrero** [doofinder/doofinder-woocommerce#209]
On the part of WP/WC, something that would help us avoid support tickets would be to detect if the client has "wordfence" installed and show a warning so that they understand that if they do not reactivate the application passwords, the indexing will not work correctly.

We have to do a test and see what is wrong with the possible plugins, compiling a list of the plugins that have this problem (the main ones)

It would also help to detect if the WP/WC API endpoints are active and accessible, since if they have been disabled they will still have indexing problems.

We will display an error message in case the blocked api is detected (for example by calling /wp-json or /config).

We have to see if we show the message before or after the installation.

**Comment by sofia-doofinder** [comment]
Victor, creo que con lo que hemos hecho del token esto ya no debería afectar, no?

**Comment by vferrero** [comment]
Correcto @sofia-doofinder ! Ahora con los nuevos endpoints ya no tendremos problemas de Auth Basic, htaccess, etc... :)
