### ISSUE TITLE
[Wordpress / Woocommerce] Landing Pages - Create landing page controller in the plugin

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-woocommerce#211]
Create a controller called landing.php in the plugin that receives two parameters through the URL. Hashid and Slug.

The controller has to load the default template that WP has and make a call to doomanager passing the hashid and the slug. 

With this information we make a call to the doomanager endpoint to get the landing page information.

This returns the H1, the content of the blocks and SEO information.

In the content of the blocks we have the query for doophoenix to get the custom results that we want to display on the screen.

Important the template we generate has to have a basic HTML structure and WP generic classes to not interfere with the theme styles.

**Comment by sofia-doofinder** [comment]
duplicated: https://github.com/doofinder/doofinder-woocommerce/issues/211
