### ISSUE TITLE
[Wordpress / Woocommerce] Generar imágenes en tamaño seleccionado

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-woocommerce#215]
Se ha reportado que a veces las indexaciones tardan mucho porque tenemos que pedirle a wordpress durante las peticiones API que genere las imágenes en un tamaño que no existe en ese momento. Por ejemplo, al realizar la primera indexación el tamaño de imagen que se solicita es de 300x300, parece que wordpress no tiene pre-generadas esas imágenes por lo que en cada petición de la API las va generando para los productos solicitados sus imágenes. Si después el cliente cambia en el plugin el tamaño de imagen a 500x500 la  próxima vez que se haga una indexación tendrá que volver a generar estas imágenes.

¿Cómo podemos mejorar esto? ¿Se podrían pre-generar esas imágenes en el momento en el que el cliente selecciona la opción en el plugin? ¿Y en el momento de instalar el plugin para que cuando la API realice las peticiones ya existan?

**Comment by vferrero** [comment]
Con el último refactor y todos los cambios que se han hecho en la nueva versión de plugin >= 2.1.0 los tiempos de indexación han mejorado notablemente. Ahora mismo el algoritmo de reescalado de imágenes es el siguiente (fichero class-thumbnail.php):

1. Obtengo las imágenes del item
2. Si el item tiene la imágen que buscamos ya generada (tanto en sus medios asociados como en su metadata), la devolvemos 
3. Si no tiene ninguna imagen, devolvemos NULL (no tiene imagen)
4. Si tiene imagen original pero no en el tamaño que necesitamos entonces reescalamos y devolvemos la URL de la imagen que hemos reescalado.

Como mejora, tal vez podríamos plantear a futuro, un cron que haga este procesado de imágenes de forma offline para así quitarle carga de trabajo al task de indexado, aunque viendo los tiempos actuales de indexado con las nuevas versiones >= 2.0.7 creo que son tiempos razonables y de momento podemos asumir esa penalización.
