### ISSUE TITLE
Disable indexing status check when the indexing response is not received

### ISSUE THREAD

**Issue by pedromcp90** [doofinder/doofinder-woocommerce#222]
## Problem

**Description:**
When the initial indexing is triggered, a check is performed every 10 seconds to update the indexing status message. If, for any reason, we do not receive a callback with the indexing status, the WordPress admin will be stuck in an infinite loop making Ajax calls to check the indexing status.

![Image](https://github.com/doofinder/doofinder-woocommerce/assets/1659534/cec1af08-1a77-469e-a80f-90c30cffea0c)

**Current Behavior:**
The system makes Ajax calls every 10 seconds to check the indexing status, until a response is received.

## Proposed Solution

After a time limit has passed, the initial indexing should be considered failed, and the checking should be disabled.

Linked issue: https://github.com/doofinder/support/issues/1828

**Comment by pedromcp90** [comment]
¿Qué opinas @CristobalDolz ?

**Comment by pedromcp90** [comment]
Sí, podríamos mostrar otro mensaje o simplemente quitar el que está a la vez que se desactiva la cmprobación.

**Comment by CristobalDolz** [comment]
¿Podría ser que el checking lo deshabilitemos porque consideremos que la indexación ha fallado pero que realmente sí que se haya indexado correctamente?

**Comment by pedromcp90** [comment]
@CristobalDolz Sería un caso muy raro, normalmente, doomanager nos responde con el resultado final de la indexación, tanto si fue bien como si hubo un error, pero sí, sería posible si la llamada que hace doomanager a WP (callback) no se recibe correctamente o si la URL del callback fuese incorrecta. Lo ideal sería poder investigar el motivo por el que no se recibió el callback.
