### ISSUE TITLE
[Wordpress] Index / No index functionality in plugin broken

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-woocommerce#237]
Parece que durante el refactor del plugin a la versión 2.0 se perdió la funcionalidad de poder indexar o no determinados posts / productos. Se va a recuperar la funcionalidad

https://github.com/doofinder/support/issues/1964

**Comment by vferrero** [comment]
Ya hemos recuperado la funcionalidad de index/noindex. Ahora si el item es noindex, el endpoint del plugin no devuelve dicho elemento y por tanto no se indexa.
