### ISSUE TITLE
[Wordpress] Modify update on save configuration

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-woocommerce#264]
Required by: https://github.com/doofinder/support/issues/2164

Actualmente el cliente tiene estas opciones a la hora de configurar el update on save en el plugin:

![Image](https://github.com/doofinder/doofinder-woocommerce/assets/92720455/e33e886f-8d51-4ea8-9d73-9a3f361d1084)

Cuando el cliente selecciona la opción `everyday` en realidad no está utilizando el update on save, si no que se deja la  modificación del feed en manos de la reindexación diaria que hace dftasks. 

Esto puede llevar a confusión a algunos clientes, por lo que se va a modificar para tener esto dividido en dos opciones:
- Update On save con un switch para activar o desactivar. Podemos mantener la etiqueta de "Update on save"
- Si está a true entonces los valores a elegir en el selector son: 90, 60, 30, 15 minutes. Utilizar la etiqueta "Process changed products"

Si hay alguna duda hablar con @CristobalDolz

**Comment by sofia-doofinder** [comment]
@CristobalDolz te parece bien la etiqueta de `update on save` para el switch y después `Process changed products` para el desplegable con las opciones?
He visto que en magento y prestasho se usa `Every 90 minutes`, `Every 60 minutes` pero en wordpress se utiliza `Each`, lo cambios para que se ane todos `every`?

**Comment by brunovesar** [comment]
@sofia-doofinder y @CristobalDolz 
Después de ver las configuraciones en las distintas plataformas me parece que la solución propuesta sigue sin ser tan comprensible para los usuarios.

El problema que veo es que el update on save de wordpress, prestashop y magento no es un update on save real.
Sinó que un CRON está ejecutandose cada cierto tiempo pidiendo al server que reindexe.
Por lo que me parece que la confusión del[ issue original ](https://github.com/doofinder/support/issues/2164)es con el label update on save.
En prestashop y magento tenemos dos labels diferentes pero ambos son más claros.
Index my products every (selector)
Automatically process product changes (selector)
Creo que lo mejor sería unificar los labels para que sean iguales en todas las plataformas.
Además el issue original dice que el boton de update now no funciona cuando el selector esta en every day. Esto es un bug y habría que arreglarlo para que el botón funcione sea cual sea el valor seleccionado en el selector.El update on save de wordpress, prestashop y magento no es un update on save real.
Sinó que un CRON está ejecutandose cada cierto tiempo pidiendo al server que reindexe.
Por lo que me parece que la confusión del[ issue original ](https://github.com/doofinder/support/issues/2164)es con el label update on save.
En prestashop y magento tenemos dos labels diferentes pero ambos son más claros.
Index my products every (selector)
Automatically process product changes (selector)
Creo que lo mejor sería unificar los labels para que sean iguales en todas las plataformas.
Además el issue original dice que el boton de update now no funciona cuando el selector esta en every day. Esto es un bug y habría que arreglarlo para que el botón funcione sea cual sea el valor seleccionado en el selector.

**Comment by sofia-doofinder** [comment]
@brunovesar lo que dices del update on save no es 100% así, es verdad que no es un update on save real porque no es que el usuario actualice un producto e instatáneamente el cambio se aplique en nuestro feed, pero no es que se reindexe todo de nuevo. Lo que hace el update on save si está puesto "cada 15 minutos" es que hay un cron que a los 15 minutos revisa qué productos han sido modificados desde el último lanzamiento y envía estos productos para ser actualizados. Es un update on save que se lanza cada X minutos, pero no para hacer una reindexación completa, si no de aquellos productos modificados.

El tema del botón de "update now" tiene sentido que no funcione cuando está en "every day" porque si el update on save está en "every day" significa que está deshabilitado y no estamos registrando los productos que se modifican, por lo que cuando se lanza no hay nada que actualizar. Por lo que este botón no debería aparecer cuando el update on save está deshabilitado.

**Comment by brunovesar** [comment]
Gracias por la aclaración!
Entiendo por qué no hace nada la opción de every day, pero el usuario seguro que no.
Yo creo que para mantener el botón deberíamos siempre registrar los productos que se modifican, aunque esté en every day.
Porque me imagino a los usuarios cambiando la setting a 15 minutos solo para darle al update now y eso no funcionara 🤦 .
Sinó podríamos modificar el every day para que diga ¨disabled¨ y en algun lado explicar que doofinder automaticamente indexara los productos cada cierto tiempo dependiendo de la configuración de admin.

**Comment by sofia-doofinder** [comment]
justo por eso viene la issue, porque los clientes ven confusos eso de "every day" y que no funcione, pero en realidad es el funcionamiento esperado porque realmente es un "disabled".

@CristobalDolz lo que proponía el otro día era tener dos botones, uno para habilitar / deshabilitar el update on save y otro para configurar el tiempo. De esta forma si el cliente lo tiene deshabilitado inicialmente, tiene que pasarlo a habilitado y configurar el tiempo, y ya tiene más sentido que hasta que no vuelvas a hacer una modificación el botón no vaya a funcionar, porque has hecho un cambio en una funcionalidad. Lo que no estoy segura es de si necesitamos los dos botones o quizás con renombrar el "every day" a "disabled" es suficiente, y ocultar el botón de "update now" cuando está como disabled.

**Comment by brunovesar** [comment]
Vale @CristobalDolz  los textos así si me parecen mucho más claros

**Comment by brunovesar** [comment]
Finalmente actualizamos los textos:
EN:
```
Feature Title: Automatically process modified products
Feature helper: Configure how often changes will be sent to Doofinder. It will only be executed if there are changes.
```
ES:
```
Feature Title: Procesar automáticamente los productos modificados
Feature helper: Configura con qué frecuencia se enviarán cambios a Doofinder. Solo se ejecutará si hay cambios.
```
FR:
```
Feature Title: Traiter automatiquement les produits modifiés
Feature helper: Configurer la fréquence à laquelle les modifications seront envoyées à Doofinder. Cela ne sera exécuté que s’il y a des changements
```
cc @CristobalDolz

**Comment by CristobalDolz** [comment]
@sofia-doofinder @brunovesar 

He estado revisando esto en general. Os pongo cómo creo que debería quedarse.

**“WHAT would success mean for that need?”**

- El Update On Save sólo está disponible en las plataformas que tenemos integración por lo que los clientes que no utilicen una plataforma o no tenga el plugin (correctamente) instalado no dispondrán del Update On Save y para indexar periódicamente tendrá que indexar el feed completo y utilizar “scheduled indexing”.
- Cuando se activa el update on save no es necesario tener activa la indexación automática completa pero esto es configurable por el cliente tener 1, otra o (¿por qué no?) las 2 aunque sea repetitivo.
    - En los casos en los que las 2 estén activos, si no hay ningún cambio en el feed a la hora de la indexación automática del admin, entonces no hay indexación y no hay consumo de requests. Pero en caso de que haya al menos 1 cambio, se procesará todo el indice.
- Explicar mejor cómo funciona la opción.

**DEFINITION:**

**Tenemos 2 formas de hacer esto según las posibilidades de la plataforma:** 

Opción A: Actualización diferida 

- Prestashop, Woocommerce, ¿?
- Se actualizan los cambios cada x tiempo según el intervalo definido.
- CAMBIOS:
    - Unificar todo en un campo. 
 
![image](https://github.com/doofinder/doofinder-woocommerce/assets/106097983/ce050fc0-6a10-41c4-ab75-108675d892e8)
    - Cambiar los textos
        - Feature Title: Update on Save: automatically process modified products
        - Feature helper: Configure how often changes will be sent to Doofinder. It will only be executed if there are changes
    - Valores en el selector:
        
        Disabled
        Each 5 min
        Each 15 min
        Each 30 min
        Each 1h
        Each 2h
        Each 6h
        Each 12h
        Once a day —> incorporar esta opción. 
        

Opción B: Actualización inmediata (Webhook) 

- Shopify, Bigcommerce, ¿?
- Se actualizan los cambios de forma inmediata tras un cambio por batches.
- SIN CAMBIOS
    - Opción para activar/Desactivar
![image](https://github.com/doofinder/doofinder-woocommerce/assets/106097983/e27c293b-7dab-4f79-9e68-346990d951a9)


Por lo tanto, deberíamos recuperar la opción para actualizar los cambios sólo de los productos modificados una vez al día "Once a day". 

@sofia-doofinder Esto deberiamos hacerlo para todas las platafomas. Dime si esta tarea podeis hacerla como mantenimiento o si la saco como tarea de producto.

**Comment by brunovesar** [comment]
@CristobalDolz 
Algo que estaría bueno tener en cuenta es que las opciones veo cambian entre las plataformas, en prestashop són hasta un máximo de 90 minutos y de ahí ya salta a (every day - Disabled) por lo que aprovecharía esta oportunidad para unificar los posibles intervalos.
También quería mencionar que la indexación update on save desde el plugin (por product id) está desincronizada con la indexación por admin.
Por lo que sí el usuario tiene las dos activadas al mismo tiempo con intervalos parecidos (plugin con la opcion `once a day` o admin con la opción `every two hours) podría llevar a una doble indexación si la indexación por admin ocurre antes que la del plugin.
Debido a este riesgo creo que deberíamos evitar las opciones más largas desde el plugin, ya que no tiene mucho sentido indexar productos por id después de una indexación completa.
Que te parece?

**Comment by CristobalDolz** [comment]
@brunovesar 

1. Sí, debemos unificar los valores para todas las plataformas (Presta, Woocommerce, Magento)

  Disabled
  Each 5 min
  Each 15 min
  Each 30 min
  Each 1h
  Each 2h
  Each 6h
  Each 12h
  Once a day —> incorporar esta opción pero que sí funcione
  
 2. Realmente un cliente que tenga el update on save no debería de indexar automaticamente el feed completo (debería dejar la indexacion desactivada), el problema es que desde el punto de vista del usuario/admin no veo forma de evitar/limitar que si el update on save está activo, no se pueda activar la indexación automática completa. 
 
Este caso que comentas: "sí el usuario tiene las dos activadas al mismo tiempo podría llevar a una doble indexación si la indexación por admin ocurre antes que la del plugin" creo que tenemos que pensar nosotros una forma de gestionarlo internamente sin que de problemas.

**Comment by brunovesar** [comment]
Bueno, lo que puedo hacer en el scope de estas tareas es unificar los textos y las opciones.
Me parece que habría que encontrar una forma de indicarle al usuario que no debe indexar automáticamente el feed si está usando la opción del update on save.
Entiendo igual que el encontrar una forma de gestionar internamente la solapación de las dos indexaciones para evitar requests de datos ya actualizados debería estar en el scope de otro issue.
También me di cuenta de que la indexación automática se hará igualmente, porque compara el hash de la última indexación y ese será diferente siempre que haya cambiado algún producto, da igual que se haya guardado antes.
cc @sofia-doofinder @CristobalDolz

**Comment by brunovesar** [comment]
Buenas @CristobalDolz 
Podrías pasarme los textos de las opciones en los distintos idiomas? (de momento necesito francés y español)

**Comment by brunovesar** [comment]
Tengo otra consulta @CristobalDolz , actualmente por defecto viene disabled (every day) ahora que opción sería la default?
Disabled?

**Comment by CristobalDolz** [comment]
Sí, a las dos. te paso la traducción y la opción Disabled sería default.

**Comment by CristobalDolz** [comment]
@brunovesar traduccion de las opciones

**Español**:

Desactivado
Cada 5 minutos
Cada 15 minutos
Cada 30 minutos
Cada 1 hora
Cada 2 horas
Cada 6 horas
Cada 12 horas
Una vez al día

**Francés**:

Désactivé
Toutes les 5 minutes
Toutes les 15 minutes
Toutes les 30 minutes
Toutes les 1 heure
Toutes les 2 heures
Toutes les 6 heures
Toutes les 12 heures
Une fois par jour

**Comment by sofia-doofinder** [comment]
@brunovesar reabro la issue porque hay que sacar la release del plugin, mañana te explica @pedromcp90  cómo se hace!

**Comment by sofia-doofinder** [comment]
Por cierto, una pregunta, lo de ocultar el botón de "Update now!" cuando el selector está en disabled se ha implementado? que no se si al final este detalle se ha quedado un poco olvidado, sólo por confirmarlo :)

**Comment by CristobalDolz** [comment]
Si el botón Update Now tambien tenemos que ocultarlo. lo daba por hecho

**Comment by brunovesar** [comment]
Tienes razon @sofia-doofinder no hice lo del boton, mañana lo miro 😓
