### ISSUE TITLE
[Wordpress] Cambiar la URL del producto padre para que coincida con la variante de menor precio

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-woocommerce#293]
Actualmente para os productos configurables estamos utilizando para el producto padre el sales price & price de la menor de sus variantes. Pero el link que estamos utilizando para este producto padre es el de "por defecto" de la plataforma, que no tiene por qué coincidir con la de menor precio, por lo que es un poco raro que el usuario vea un precio en la capa y al hacer click le lleve a otra de las variantes. Vamos a modificarlo para que el link del producto padre sea el mismo de la variante de menor precio.

**Comment by ogomezba** [comment]
@alexsomet  Buenas Alex! Ya está disponible la nueva versión para el plugin de wordpress que indexa el producto padre con la URL de la variante con el mínimo precio.

Un saludo!
