### ISSUE TITLE
Update on save needs some fixes

### ISSUE THREAD

**Issue by eugeniobonifacio** [doofinder/doofinder-woocommerce#313]
Hello,

I've been struggling with the "update on save" cron not working. I found a couple of issues that need to be fixed:

1. Cron schedules must be registered always, not only when in the admin interface. Otherwise the cron schedule is being deleted.
2. The Endoint API uses the underlaying Woocommerce API. However inside a cron job there's no user, which results in a 401 error code.

I temporary fixed them using the following hooks:

```
add_filter('woocommerce_rest_check_permissions', function ( $permission, $context, $object_id, $post_type ) {
if(wp_doing_cron() && $context === 'read' && doing_filter('doofinder_update_on_save')) {
        return true;
    }

    return $permission;
}, 100, 4);

add_filter('init', function () {
    if(!is_admin()) {
        add_filter( 'cron_schedules', array( Settings::class, 'add_schedules' ), 100, 1 );
    }
});
```

I hope this can be helpful to improve the plugin.

**Comment by eugeniobonifacio** [comment]
Sorry, the 'init' hook is not a filter but an action:

```
add_action('init', function () {
    if(!is_admin()) {
        add_filter( 'cron_schedules', array( Settings::class, 'add_schedules' ), 100, 1 );
    }
});
```

**Comment by juan-gm** [comment]
The new version with the fix has been deployed. It is version 2.5.7.

**Comment by davidmolinacano** [comment]
Good morning @eugeniobonifacio ! Thank you very much for your suggestions. Regarding the last one you mention about `cron_schedules` I think it has already been solved here: https://github.com/doofinder/doofinder-woocommerce/pull/323/files#diff-6de0a4988b16dc6efb250da24e08311b61d1c7c89397608a8100a58f9f5c0391. The filter is added always, so this time is not only added on admin screens.

**Comment by eugeniobonifacio** [comment]
Oh, then I'm sorry, I didn't have notice it. Thank you!

**Comment by davidmolinacano** [comment]
Oh, no need to apologize, in fact you have helped us a lot with your suggestions!! :raised_hands: Thank you very much!! :smile:
