### ISSUE TITLE
[Wordpress] Mejorar error en update on save

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-woocommerce#328]
Ticket related: https://github.com/doofinder/support/issues/2588

Hay un cliente al que a veces le falla el update on save, parece que es por un problema de su servidor que cuando se hacen las consultas de los productos da un error y nosotros lo estamos camuflando.

~~Deberíamos mejorar nuestro código y:~~
- [ ] ~~En caso de que la petición falle hacer un retry~~
- [ ] ~~En caso de que los retries fallen devolver un error~~

~~También queda raro que aquí estamos mandando un bulk de 100 pero después en dooplugins se gestiona de 90 en 90, podríamos ajustar el bulk aquí a 90.~~

Resulta que al final la causa de que fallara WP era que el cron se estaba ejecutando en un contexto sin usuario, por lo que al hacer la petición a la API de WP esta devolvía un 401 (unauthorized).

**Comment by sofia-doofinder** [comment]
@juan-gm dejo por aquí esta issue que nos había creado un usuario relacionado con este problema https://github.com/doofinder/doofinder-woocommerce/issues/313. Lo comentamos el lunes cuando vuelvas de vacaciones, @davidmolinacano cree que puede ser una buena alternativa.

**Comment by juan-gm** [comment]
Cuando realizamos un update on save, el flujo es el siguiente:

1. Se lanza una action (doofinder_update_on_save)
2. Esta tarea lee de una tabla los ids de los productos que han sido modificados
3. Obtiene los datos de estos ids y los envía a dooplugins

Es este paso 3 el que estaba dando problemas. Para obtener los datos de los productos utiliza la función `get_items` que se encuentra en el archivo `class-endpoint-custon.php`. Esta función a su vez llamaba a la API interna de Wordpress con `WP_REST_Request`, y esta llamada a veces fallaba, causandoq eu el update on save fallara también.

La razón de que a veces fallara es que hay dos maneras de que se ejecute el update on save. Una de ellas es pulsando el botón de "update now" que aparece en el admin de WP y otra es esperando al cron que se ejecuta cada X tiempo (según esté configurado en el panel del admin).

Cuando se ejecutaba pulsando el botón desde el admin la petición a la API de Wordpress se hacía desde el contexto del usuario logueado en el admin, por lo que funcionaba correctamente. Pero cuando se hacía desde el cron, el contexto no tenía usuario y por tanto la petición fallaba. Hemos modificado el código permitiendo peticiones sin autenticar a la API de WP cuando estuviéramos haciendo el update on save para que esto no pase (se puede ver el cambio en la PR asociada).
