### ISSUE TITLE
[Wordpress] Different name df_variants_information than variant attribute

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-woocommerce#329]
Se ha visto que para el cliente 93b79984ad27793d5c7fc749a7254a38 hay algo raro en la indexación del campo `df_variants_information` del producto padre y en lo que son los atributos de la variante.

Producto de ejemplo: Cama Box + Colchão Simmons Central Park Neo (https://simmons.com.br/cama-box-colchao-simmons-central-park-neo.html). Este producto es configurable en tamaño (campo `medidas`):
![Image](https://github.com/user-attachments/assets/42014a6f-d13c-438d-8de3-955cbee8bc7d)

Viendo el valor de `df_variants_information` vemos que tiene como elemento `medidas`:
![Image](https://github.com/user-attachments/assets/f99a698a-e556-4549-8679-02e2a0347854)

Pero si miramos la variante no tiene un atributo que sea `medidas` si no `colchon_medidas`:
![Image](https://github.com/user-attachments/assets/08bd43f3-0127-4f5a-93ef-d7b9a169a400)

al no coincidir los nombres esto provocará que el botón del add to cart no funcione correctamente porque busca en las variantes por el valor definido en `df_variants_information`.

**Comment by davidmolinacano** [comment]
✅ Proposal validated by @sofia-doofinder ✅ 

Basically, the idea is to retrieve the attribute mapping from the settings (stored in `wp_options` table) and check if a custom naming has been applied. In that case, we will use that name in the `df_variants_information`.
